export const PROMPT_NOUNS = [
  'penguin',
  'toaster',
  'dentist',
  'robot',
  'cactus',
  'pirate',
  'wizard',
  'octopus',
  'astronaut',
  'raccoon',
  'dragon',
  'librarian',
  'surfer',
  'ninja',
  'giraffe',
  'detective',
  'mermaid',
  'chef',
  'vampire',
  'frog',
] as const

export const PROMPT_ACTIONS = [
  'late for work',
  'surfing',
  'on fire',
  'juggling socks',
  'riding a unicycle',
  'eating spaghetti',
  'stuck in traffic',
  'doing karaoke',
  'baking cookies',
  'fighting a kite',
  'wearing flippers',
  'lost in a mall',
  'painting a fence',
  'riding an escalator',
  'chasing a balloon',
  'reading the news',
  'building a sandcastle',
  'stuck in a tree',
  'playing the drums',
  'walking a lobster',
] as const
